env:
  node: true
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - plugin:prettier/recommended 
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  "semi": ["error", "always"],
  "@typescript-eslint/no-var-requires": 0,
}
